spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpa
    username: sa
    password:
    driver-class-name: org.h2.Driver
  security:
    user:
      name: user
      password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

  mvc:
    hiddenmethod:
      filter:
        enable: true

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace

